# coding=utf8
"""
drama.py - Creates drama wherever you go!
Copyright 2014 Max Gurela

Licensed under the Eiffel Forum License 2.
"""
from __future__ import unicode_literals
from willie import web
from willie.module import commands
import re
import random

finder = re.compile(r'.*<h1>(.+?)<\/h1>.*')

phrases = ["%people% implements a system into %thing% that %action%",
    "%people% launched a DoS attack on the website of %thing%",
    "%site% urges everyone to stop using %thing%",
    "After a %enormous% amount of requests, %pack% removes %thing%",
    "After a %enormous% amount of requests, %pack% adds %thing%",
    "After a %enormous% amount of requests, %pack% adds %function% to %thing%",
    "%people% plays %thing% on Twitch",
    "%people% fixes %function% in %thing% to be unlike %thing%",
    "%thing% makes %thing% %crash%, %site% users complain",
    "%people% complained about being in %thing% on %site%",
    "%people% releases %code% of %thing% for %price%",
    "%site% considers %thing% worse than %thing%",
    "%people% made %thing% depend on %thing%",
    "%people% bans %people% from using %thing% in %pack%",
    "%people% complains that %thing% discussion doesn't belong on %site%",
    "%people% has a Patreon goal to add %function% to %thing% for %price% a month",
    "%people% has a Patreon goal to add %thing% compatibility to %thing% for %price% a month",
    "%people% complains that %people% replaced %thing% by %thing%",
    "%people% complains that %people% replaced %thing% by %thing% in %pack%",
    "%people% complains that %people% removed %function% in %pack%",
    "%people% decided that %thing% is too %adjective% and replaced it with %thing%",
    "%people% %says% %thing% is %adjective%.",
    "%people% %says% %thing% is literally %adjective%.",
    "%thing% is not updated for the latest version of Minecraft.",
    "%people% removes %thing% from %pack%.",
    "%people% adds %thing% to %pack%.",
    "%people% quits modding. Fans of %thing% rage.",
    "%people% is found to secretly like %thing%",
    "%people% openly hates %function% in %thing%",
    "%people% threatens to %ac1% %people% until they remove %thing% from %pack%",
    "%people% threatens to %ac1% %people% until they remove %function% from %thing%",
    "%people% threatens to %ac1% %people% until they add %function% to %thing%",
    "%people% came out in support of %thing%",
    "%people% came out in support of %drama%",
    "%people% and %people% came out in support of %drama%",
    "%people% came out against %drama%, %site% rages",
    "%people% and %people% came out against %drama%, %site% rages",
    "%people% forks %thing% causing %drama%",
    "%people% %says% to replace %thing% with %thing%",
    "%people% %says% %people% causes drama",
    "%thing% fans claim that %thing% should be more like %thing%",
    "%thing% fans claim that %thing% should have better %function%",
    "%people% %says% that %thing% should be more like %thing%",
    "%people% %says% that %thing% should be less like %thing%",
    "%people% rebalances %thing% for %pack%",
    "%people% adds %function% to %thing% by request of %people%",
    "%people% removes %function% from %thing% by request of %people%",
    "%people% removes compatibility between %thing% and %thing% by request of %people%",
    "%people% %says% %people%'s attitude is %adjective%",
    "%people% %says% %site%'s attitude is %adjective%",
    "%people% quits the development team of %thing%",
    "%people% %says% %thing% is too much like %thing%",
    "%people% %says% %thing% is a ripoff of %thing%",
    "%people% %says% %people% stole %code% from %people%",
    "%people% %says% %people% did not steal %code% from %people%",
    "%people% decides to %ban% %people% from %pack%",
    "%thing% doesn't work with %thing% since the latest update",
    "%people% sues %thing%",
    "%people% %says% %thing% is %adjective% on %site%",
    "%people% %says% %thing% is full of %badsoft%",
    "%people% %says% %thing% causes %drama%",
    "%people% %says% %thing% causes %drama% when used with %thing%",
    "%people% %says% using %thing% and %thing% together is %adjective%",
    "%people% rants about %thing% on %site%",
    "%people% rants about %function% in mods on %site%",
    "%people% steals code from %thing%",
    "%thing% breaks %function%",
    "%people% sues %thing% developers",
    "%people% reminds you that %thing% is %adjective%",
    "%people% and %people% get into a drama fight on %site%",
    "Fans of %thing% and %thing% argue on %site%",
    "%people% and %people% argue about %thing%",
    "%people% puts %badsoft% in %thing%",
    "%people% complains about %thing% breaking %thing%",
    "%people% complains about %thing% breaking %function%",
    "%people% complains about %thing% including %function%",
    "%thing% breaks %function% in %thing%",
    "%thing% breaks %thing% support in %thing%",
    "%thing% adds code to %ban% %people% automatically",
    "%thing% adds code to %ban% people using %thing%",
    "%thing% removes compatibility with %thing%",
    "%people% %says% not to use %thing%",
    "%people% %says% not to use %thing% with %thing%",
    "%people% finds %badsoft% in %thing%",
    "%people% drew a nasty graffiti about %people%",
    "%people% drew a nasty graffiti about %thing%",
    "%thing% makes %thing% %crash% when used with %thing%",
    "%thing% makes %thing% %crash% when used by %people%",
    "%thing% makes %thing% crash %thing% when used by %people%",
    "%thing% adds %badsoft% that only %activates% in %pack%",
    "%thing% adds %badsoft% that only %activates% alongside %thing%",
    "%thing% makes %people% invincible from %thing% in %pack%",
    "%people% decides to base their entire modpack on %thing%",
    "%people% tweaks balance in %thing% too much, annoying %site%",
    "%people% tweaks balance in %thing% too much, annoying %people%",
    "%people% %says% %people% is worse than %people%",
    "%people% %says% %thing% is %worse% than %thing%",
    "%people% bans %people% from %site%"]

parts = {
  "ac1": [
    "sue",
    "destroy the life of",
    "flame",
    "cause drama about",
    "complain about",
    "kick"
  ],
  "action": [
    "enables %badsoft%",
    "%bans% %people%",
    "auto-downloads %badsoft%",
    "disables %code%"
  ],
  "activates": [
    "activates",
    "works",
    "functions",
    "breaks"
  ],
  "adjective": [
    "bad",
    "wrong",
    "illegal",
    "horrible",
    "nasty",
    "not in ForgeCraft",
    "noncompliant with Mojang's EULA",
    "a serious problem",
    "incompatible",
    "a waste of time",
    "wonderful",
    "amazing",
    "toxic",
    "too vanilla",
    "shameful",
    "disappointing",
    "bloated",
    "outdated",
    "incorrect",
    "full of drama",
    "too realistic"
  ],
  "badsoft": [
    "malware",
    "spyware",
    "adware",
    "DRM",
    "viruses",
    "trojans",
    "keyloggers",
    "stolen code",
    "easter eggs",
    "potential login stealers",
    "adf.ly links",
    "bad code",
    "stolen assets",
    "malicious code",
    "secret backdoors"
  ],
  "ban": [
    "ban",
    "kick",
    "put a pumpkin of shame on",
    "add items mocking",
    "blacklist",
    "whitelist",
    "give admin rights to",
    "shame",
    "destroy"
  ],
  "code": [
    "code",
    "assets",
    "ideas",
    "concepts",
    "a single function",
    "5 lines of code",
    "a class",
    "a few files",
    "a ZIP file",
    "Gradle buildscripts",
    "a GitHub repository"
  ],
  "crash": [
    "crash",
    "explode",
    "break",
    "lag",
    "blow up",
    "corrupt chunks",
    "corrupt worlds",
    "rain hellfish",
    "spawn bees"
  ],
  "drama": [
    "bugs",
    "crashes",
    "drama",
    "lots of drama",
    "imbalance",
    "pain and suffering",
    "piracy",
    "bees",
    "adf.ly"
  ],
  "enormous": [
    "big",
    "large",
    "huge",
    "gigantic",
    "enormous"
  ],
  "function": [
    "MJ support",
    "RF support",
    "EU support",
    "FMP compatibility",
    "quarries",
    "automatic mining",
    "GregTech balance",
    "ComputerCraft APIs",
    "OpenComputers APIs",
    "Bukkit plugin compatibility",
    "MCPC+ support",
    "ID allocation",
    "ore processing",
    "smelting",
    "crafting",
    "balance",
    "bees",
    "ThaumCraft integration",
    "realism",
    "decorative blocks",
    "new mobs",
    "TCon tool parts",
    "new wood types",
    "bundled cable support",
    "new player capes",
    "more drama",
    "less drama",
    "microblocks",
    "drama generation commands",
    "Blutricity support",
    "overpowered items",
    "underpowered items",
    "new ores",
    "better SMP support",
    "achievements",
    "quests",
    "more annoying worldgen"
  ],
  "pack": [
    "Feed The Beast",
    "the ForgeCraft pack",
    "FTB Monster",
    "FTB Unstable",
    "Agrarian Skies",
    "Direwolf20 Pack",
    "Tekkit",
    "Hexxit",
    "ATLauncher",
    "Resonant Rise",
    "MCUpdater",
    "Attack of the B-Team",
    "Mindcrack",
    "Magic Maiden",
    "ForgeCraft",
    "Technic"
  ],
  "people": [
    "Player",
    "jadedcat",
    "Alblaka",
    "Greg",
    "Eloraam",
    "AUTOMATIC_MAIDEN",
    "Alz454",
    "RS485",
    "Shukaro",
    "Toops",
    "CovertJaguar",
    "Pahimar",
    "Sengir",
    "Azanor",
    "jeb",
    "Greymerk",
    "Dinnerbone",
    "Grum",
    "dan200",
    "Cloudy",
    "KingLemming",
    "Zeldo",
    "AlgorithmX2",
    "Mikee",
    "Eyamaz",
    "kakermix",
    "cpw",
    "LexManos",
    "Vswe",
    "Direwolf20",
    "Calclavia",
    "Reika",
    "Sangar",
    "skyboy",
    "FlowerChild",
    "SpaceToad",
    "ChickenBones",
    "Notch",
    "Pokefenn",
    "Shadowclaimer",
    "Vazkii",
    "pixlepix",
    "nekosune",
    "copygirl",
    "immibis",
    "RichardG",
    "JAKJ",
    "mDiyo",
    "pillbox",
    "progwml6",
    "PowerCrystals",
    "GUIpsp",
    "nallar",
    "Soaryn",
    "Soaryn",
    "AbrarSyed",
    "Sunstrike",
    "BevoLJ",
    "asie",
    "tterrag",
    "CrazyPants",
    "Aidan",
    "Binnie",
    "Mojang",
    "ProfMobius",
    "peterix",
    "RWTema",
    "Slowpoke",
    "Curse",
    "bspkrs",
    "Mr_okushama",
    "Searge",
    "iChun",
    "Krapht",
    "Erasmus_Crowley",
    "MysteriousAges",
    "Drullkus",
    "Micdoodle8",
    "GenPage",
    "Hunterz",
    "tgame14",
    "Velotican",
    "kirindave",
    "MachineMuse",
    "M3gaFr3ak",
    "Lunatrius",
    "wha-ha-ha",
    "maxpowa",
    "boni",
    "meew0",
    "Glassmaker",
    "sk89q",
    "Kubuxu"
  ],
  "price": [
    "$200",
    "$250",
    "$300",
    "$350",
    "$400",
    "$450",
    "$500",
    "$600",
    "one million dollars"
  ],
  "says": [
    "says",
    "tweets",
    "claims",
    "confirms",
    "denies"
  ],
  "site": [
    "FTB Forums",
    "MCF",
    "Reddit",
    "4chan",
    "Technic Forums",
    "IC2 Forums",
    "GitHub",
    "BitBucket",
    "IRC",
    "ForgeCraft",
    "Patreon",
    "BTW Forums",
    "GregTech thread",
    "Google+",
    "Twitch"
  ],
  "thing": [
    "NOVA",
    "ForgeCraft",
    "Simply Jetpacks",
    "RedPower 2",
    "ModLoader",
    "RedLogic",
    "Forge MultiPart",
    "Project: Red",
    "BuildCraft",
    "Tinkers' Steelworks",
    "Artifice",
    "Roguelike Dungeons",
    "IndustrialCraft 2",
    "Equivalent Exchange",
    "Forestry",
    "RailCraft",
    "Simple Jetpacks",
    "Compact Solars",
    "ComputerCraft",
    "Wireless Redstone",
    "OpenComputers",
    "GregTech",
    "Ars Magica",
    "Thaumcraft",
    "FTB",
    "Technic",
    "Resonant Rise",
    "MineFactory Reloaded",
    "Magic Farm 2",
    "Tekkit",
    "MCPC+",
    "ATLauncher",
    "Metallurgy",
    "Logistics Pipes",
    "MCUpdater",
    "MultiMC",
    "Curse",
    "Mojang",
    "Test Pack Please Ignore",
    "Agrarian Skies",
    "Steve's Carts",
    "Steve's Factory Manager",
    "BiblioCraft",
    "Minecraft",
    "XyCraft",
    "Forge",
    "GregTech",
    "OpenBlocks",
    "OpenPeripheral",
    "OpenComputers",
    "MFFS",
    "RotaryCraft",
    "Big Reactors",
    "Thermal Expansion 3",
    "Extra Utilities",
    "Universal Electricity",
    "Not Enough Items",
    "Portal Gun mod",
    "the Mojang launcher",
    "Too Many Items",
    "OptiFine",
    "Extra Cells",
    "ExtraBiomesXL",
    "Biomes O' Plenty",
    "Better than Wolves",
    "Schematica",
    "Tinker's Construct",
    "Natura",
    "Hexxit",
    "Iron Chests",
    "An open-source mod",
    "A closed-source mod",
    "Not Enough Mods",
    "Ender IO",
    "Mekanism",
    "Minecraft 1.7",
    "Pixelmon",
    "Pixelmon",
    "JABBA",
    "WAILA",
    "Opis",
    "CraftGuide",
    "Iguana Tweaks",
    "Tinkers Mechworks",
    "the Minecraft Drama Generator",
    "MineChem",
    "LittleMaidMob",
    "MCP",
    "Immibis' Microblocks",
    "Carpenter's Blocks",
    "Chisel",
    "Applied Energistics",
    "Applied Energistics 2",
    "Rotatable Blocks",
    "EnhancedPortals 3",
    "Ex Nihilo",
    "Ex Aliquo",
    "Magic Bees",
    "BetterStorage",
    "Backpacks",
    "Aether II",
    "Highlands",
    "Alternate Terrain Generation",
    "InfiCraft",
    "Bukkit",
    "Spigot",
    "SpoutCraft",
    "MortTech",
    "ICBM",
    "Galacticraft",
    "Modular Power Suits",
    "Team CoFH",
    "Extra Bees",
    "Extra Trees",
    "Mo' Creatures",
    "Grimoire of Gaia",
    "Atum",
    "Agriculture",
    "Sync",
    "Hats",
    "Nether Ores"
  ],
  "worse": [
    "worse",
    "better",
    "faster",
    "slower",
    "more stable",
    "less buggy"
  ]
}

token = re.compile(r'%(.+?)%')


def setup(bot):
    parts['thing'] = [(thing[:1] + u'\u200B' + thing[1:]) for thing in parts['thing']]
    parts['people'] = [(person[:1] + u'\u200B' + person[1:]) for person in parts['people']]


def replace_tokens(input, used=[]):
    result = token.search(input)
    if not result or not result.group(1):
        return input
    obj = result.group(1)
    repl = random.choice(parts[obj])
    while (repl in used):
        repl = random.choice(parts[obj])
    used.append(repl)
    input = input.replace('%' + obj + '%', repl, 1)
    return replace_tokens(input, used)


@commands('drama')
def drama(bot, trigger):
    headers = {
         'User-Agent': 'Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11'
    }
    raw = web.get('http://asie.pl/drama.php?2', timeout=10, headers=headers)
    #bot.say(raw)
    try:
        words = finder.search(raw).group(1).split()
        out = []
        for word in words:
            out.append(word[:1] + u'\u0081' + word[1:])
        bot.say(' '.join(out))
    except Exception:
        if (trigger.nick.lower() == "asie"):
            bot.say('418 I\'m a teapot')
            return
        bot.say(replace_tokens(random.choice(phrases)))
        #bot.say('418 I\'m a teapot')
